services:
  # A Docker web service
  - type: web
    name: cloud-web
    region: frankfurt
    plan: free
    runtime: node
    repo: https://github.com/khaledbs17/render-deploy-bp
    branch: master
    buildCommand: npm install
    startCommand: nmp start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString

databases:
  # db 1
  - name: cloud-db
    region: frankfurt
    plan: free
    databaseName: cloud
    user: cloud 